# Usage
#      - name: Generate LICENSES.toml
#        id: licenses
#        uses: ./.github/actions/licenses-gen
#      - run: echo "$LICENSE" > ./LICENSE.toml
#        shell: bash
#        env:
#          LICENSE: ${{ steps.licenses.outputs.licenses }}

name: Generate Licenses
description: Generate licenses.toml

inputs:
  output_path:
    description: "Path to save LICENSES.toml. default: `./LICENSES.toml`"
    default: ./LICENSES.toml
outputs:
  licenses:
    description: "LICENSES.toml data"
    value: ${{ steps.license.outputs.licenses }}

runs:
  using: "composite"
  steps:
    - name: Install cargo-license
      shell: bash
      run: |
        cargo install cargo-license
        cargo install bundle-licenses

    - name: Generate LICENSES.toml
      shell: bash
      id: license
      run: |
        echo '# SPDX-License-Identifier: Apache-2.0 OR MIT' > $GITHUB_OUTPUT
        echo '# SPDX-FileCopyrightText: (C) 2024 SARDONYX' >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT

        echo '# Generated by `$cargo license --color never >> $(GITHUB_OUTPUT)`' >> $GITHUB_OUTPUT
        echo 'third_party_license_list = """' >> $GITHUB_OUTPUT
        cargo license --color never >> $GITHUB_OUTPUT
        echo '"""' >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT

        echo '# Generated by `$cargo bundle-licenses >> $(GITHUB_OUTPUT)`' >> $GITHUB_OUTPUT
        cargo bundle-licenses >> $GITHUB_OUTPUT
