# Usage
#    - name: Generate LICENSES.toml
#      uses: ./.github/actions/licenses-gen
#      with:
#        output_path: ./LICENSES.toml

name: Generate Licenses
description: Generate licenses.toml

inputs:
  output_path:
    description: "Path to save LICENSES.toml. default: `./LICENSES.toml`"
    default: ./LICENSES.toml

runs:
  using: "composite"
  steps:
    - name: Install cargo-license
      shell: bash
      run: |
        cargo install cargo-license
        cargo install cargo-bundle-licenses

    # NOTE: $GITHUB_OUTPUT is an environment variable, so to output arbitrary multi-line text, you must specify a file.
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
    - name: Generate LICENSES.toml
      shell: bash
      id: licenses
      run: |
        echo '# SPDX-License-Identifier: Apache-2.0 OR MIT' > ${{ inputs.output_path }}
        echo '# SPDX-FileCopyrightText: (C) 2024 SARDONYX' >> ${{ inputs.output_path }}
        echo "" >> ${{ inputs.output_path }}

        echo '# Generated by `$cargo license --color never >> $(inputs.output_path)`' >> ${{ inputs.output_path }}
        echo 'third_party_licenses = """' >> ${{ inputs.output_path }}
        cargo license --color never >> ${{ inputs.output_path }}
        echo '"""' >> ${{ inputs.output_path }}
        echo "" >> ${{ inputs.output_path }}

        echo '# Generated by `$cargo bundle-licenses >> $(inputs.output_path)`' >> ${{ inputs.output_path }}
        cargo bundle-licenses -f toml >> ${{ inputs.output_path }} 2>/dev/null  # ignore warnings
