name: Build(CLI)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

env:
  APP_NAME: hkxc
  CARGO_TERM_COLOR: always
  PROFILE: release-lto

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        job:
          # default features
          - {
              target: aarch64-apple-darwin,
              os: macos-latest,
              asset: serde-hkx-cli-aarch64-apple-darwin.tar.gz,
            }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              asset: serde-hkx-cli-x86_64-pc-windows-msvc.zip,
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              asset: serde-hkx-cli-x86_64-unknown-linux-gnu.tar.gz,
            }

          # extra_fmt(json) features
          - {
              target: aarch64-apple-darwin,
              os: macos-latest,
              asset: serde-hkx-cli-aarch64-apple-darwin-extra_fmt.tar.gz,
              features: extra_fmt,
            }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-latest,
              asset: serde-hkx-cli-x86_64-pc-windows-msvc-extra_fmt.zip,
              features: extra_fmt,
            }
          - {
              target: x86_64-unknown-linux-gnu,
              os: ubuntu-latest,
              asset: serde-hkx-cli-x86_64-unknown-linux-gnu-extra_fmt.tar.gz,
              features: extra_fmt,
            }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build and Compress
        uses: ./.github/actions/build-and-compress
        with:
          target: ${{ matrix.job.target }}
          profile: ${{ env.PROFILE }}
          app_name: ${{ env.APP_NAME }}
          asset_name: ${{ matrix.job.asset }}
          features: ${{ matrix.job.features }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ matrix.job.asset }}
          path: ./build/
